
# # service, headless service, statefulset, pvc
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb
#   namespace: roboshop
# spec:
#   selector:
#     project: roboshop
#     component: mongodb
#     tier: db
#   ports:
#     - protocol: TCP
#       port: 27017 # service port
#       targetPort: 27017 # container port
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb-headless
#   namespace: roboshop
# spec:
#   clusterIP: None
#   selector:
#     project: roboshop
#     component: mongodb
#     tier: db
#   ports:
#     - protocol: TCP
#       port: 27017 # service port
#       targetPort: 27017 # container port
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mongodb
#   namespace: roboshop
# spec:
#   selector:
#     matchLabels:
#       project: roboshop
#       component: mongodb
#       tier: db
#   serviceName: "mongodb-headless" # this should be head less service name
#   replicas: 2 # by default is 1
#   template:
#     metadata:
#       labels:
#         project: roboshop
#         component: mongodb
#         tier: db
#     spec:
#       containers:
#       - name: mongodb
#         image: joindevops/mongodb:v1
#         volumeMounts:
#         - name: mongodb
#           mountPath: /data/db
#   # This is PVC
#   volumeClaimTemplates:
#   - metadata:
#       name: mongodb
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       storageClassName: "roboshop-ebs"
#       resources:
#         requests:
#           storage: 1Gi


# -------------------------------
# 1. HEADLESS SERVICE (for StatefulSet)
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
spec:
  clusterIP: None        # Headless service
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80

---
# -------------------------------
# 2. CLUSTERIP SERVICE (normal Service)
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80

---
# -------------------------------
# 3. PERSISTENT VOLUME CLAIM
# -------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# -------------------------------
# 4. STATEFULSET
# -------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  serviceName: nginx-headless   # Must point to headless service
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-storage
            mountPath: /usr/share/nginx/html  # sample data directory
  volumeClaimTemplates:
    - metadata:
        name: nginx-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
