# ------------------------------------
# 1. Namespace
# ------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
  labels:
    project: roboshop
---
# ------------------------------------
# 2. Secret for MySQL Root Password
# ------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
  labels:
    project: roboshop
type: Opaque
data:
  # root password: roboshop123
  MYSQL_ROOT_PASSWORD: cm9ib3Nob3AxMjM=
---
# ------------------------------------
# 3. Headless Service
# ------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
spec:
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
# ------------------------------------
# 4. ClusterIP Service
# ------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
spec:
  type: ClusterIP
  selector:
    app: mysql
    project: roboshop
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
# ------------------------------------
# 5. StatefulSet
# ------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: roboshop
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
      labels:
        project: roboshop
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: gp3
